apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: msa-demo
resources:
  - namespace.yaml
  - mysql.yaml
  - user-service.yaml
  - order-service.yaml
  - api-gateway.yaml
  - ingress.yaml
