CREATE DATABASE IF NOT EXISTS msa_user CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS msa_order CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
GRANT ALL PRIVILEGES ON msa_user.* TO 'msa'@'%';
GRANT ALL PRIVILEGES ON msa_order.* TO 'msa'@'%';
FLUSH PRIVILEGES;
